#!/bin/sh

if [ $1 ] 
then
  gethost-mackerel.rb --service $1 | percol | cut -d ',' -f 1  | cut -d ':' -f 2 |  pbcopy && ssh `pbpaste`
else
  gethost-mackerel.rb | percol | cut -d ',' -f 1  | cut -d ':' -f 2 |  pbcopy && ssh `pbpaste`
fi
